### ISSUE TITLE
Odvečni znaki (README in PDF).

### ISSUE THREAD

**Issue by hunter1749** [jureslak/Gimnazijska-snov-matematike#7]
PDF:
* V `25.3 Deljenje polinomov` je **ekstra zaklepaj** pri stopnji q.

![image](https://github.com/jureslak/Gimnazijska-snov-matematike/assets/44819251/d5713cd2-02a6-4101-9c8b-0169443d59e4)

README:
* **knajbolje**
* **nevarja**

Ne vidim, da bi bil kdo tu še dejaven, je pa zadeva super uporabna 🙂👍.

**Comment by jureslak** [comment]
Tole je bilo pa presenečenje, me veseli, da je to še vedno v uporabi :) Sem popravil, če mi poveš ime, te dodam še v PDF.

**Comment by hunter1749** [comment]
Lahko, Ian mi je ime.
